### ISSUE TITLE
`aliyunsdkcore` depends on deprecated `pycrypto` (should use `pycryptodome` instead)*

### ISSUE THREAD

**Issue by lzwjava** [aliyun/aliyun-openapi-python-sdk#546]
### Error Stack

```shell
$ pip install aliyunsdkcore

...
      configure: creating ./config.status
      config.status: creating src/config.h
      src/_fastmath.c:33:10: fatal error: longintrepr.h: No such file or directory
         33 | #include <longintrepr.h>                                /* for conversions */
            |          ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycrypto
  Running setup.py clean for pycrypto
Failed to build pycrypto
ERROR: Failed to build installable wheels for some pyproject.toml based projects (pycrypto)
```

### **Short Description**  
The `aliyunsdkcore` package depends on `pycrypto>=2.6.1`, which is **deprecated, unmaintained, and fails to build on Python 3.13+** due to missing internal Python headers (`longintrepr.h`).  

**Impact:**  
- Breaks installations on modern Python versions (3.13+).  
- Security risk due to unpatched vulnerabilities in `pycrypto`.  

**Suggested Fix:**  
Replace `pycrypto` with the maintained fork **[`pycryptodome`](https://www.pycryptodome.org/)** (API-compatible drop-in replacement).  

**Reproduction Steps:**  
1. Install `aliyunsdkcore` on Python 3.13.  
2. Observe build failure due to `pycrypto` dependency.  

**Workaround:**  
Manually install `pycryptodome` and remove `pycrypto`, but this should be fixed upstream.  

---

### **Additional Notes for the Report**  
- Link to `pycrypto` deprecation: [PyPI](https://pypi.org/project/pycrypto/)  
- `pycryptodome` is the recommended alternative (used by `paramiko`, `google-auth`, etc.).  
- Example error:  
  ```plaintext
  src/_fastmath.c:33:10: fatal error: longintrepr.h: No such file or directory
  ```  

This change would improve compatibility and security. Thanks for maintaining the SDK!  

---

### **Where to Report?**  
- **GitHub:** [aliyun/aliyun-openapi-python-sdk](https://github.com/aliyun/aliyun-openapi-python-sdk)  
- **Aliyun SDK Docs:** [OpenAPI SDK](https://next.api.aliyun.com/)  

Let me know if you'd like help drafting a full PR!

**Comment by chenhz01** [comment]
Thanks for the maintainer reply pointing to aliyun-python-sdk-core — useful context. For anyone staying on the current line: `longintrepr.h` was removed from the public C API in Python 3.11, so any source build of pycrypto dies right there — the dependency isn't just deprecated, it's effectively uninstallable on modern Python. For the common AES/DES paths pycryptodome is API-compatible as a drop-in, so since aliyunsdkcore seems to use pycrypto only for a narrow helper, a vendored replacement might be even safer than a new version pin. Does aliyun-python-sdk-core cover the same helper surface, or would the core package still pull pycrypto transitively?

**Comment by CodeSpaceiiii** [comment]
> Thanks for the maintainer reply pointing to aliyun-python-sdk-core — useful context. For anyone staying on the current line: `longintrepr.h` was removed from the public C API in Python 3.11, so any source build of pycrypto dies right there — the dependency isn't just deprecated, it's effectively uninstallable on modern Python. For the common AES/DES paths pycryptodome is API-compatible as a drop-in, so since aliyunsdkcore seems to use pycrypto only for a narrow helper, a vendored replacement might be even safer than a new version pin. Does aliyun-python-sdk-core cover the same helper surface, or would the core package still pull pycrypto transitively?

we have received your question. We will evaluate the situation soon to see how to replace this package.
